language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer update

script:
  - php ./vendor/bin/phpunit -c ./tests/.

after_script:
  - php vendor/bin/coveralls -v
